# Generated by Django 5.1.1 on 2024-09-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('ClaimName', models.CharField(max_length=255)),
                ('Verified', models.BooleanField(default=False)),
            ],
        ),
    ]
